// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKUUkZm6fN_AFKevUOuaMKRvQwIouVjqo',
    appId: '1:377588042401:web:1d54a71c82447eff363ee0',
    messagingSenderId: '377588042401',
    projectId: 'ecommers-e76c4',
    databaseURL: "https://ecommers-e76c4-default-rtdb.firebaseio.com/",
    authDomain: 'ecommers-e76c4.firebaseapp.com',
    storageBucket: 'ecommers-e76c4.appspot.com',
    measurementId: 'G-CJMH1K10K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfAlnpLP3JFtNJr-16b-mBVADRcHXdLS8',
    appId: '1:377588042401:android:c9a28ab07ad29e96363ee0',
    messagingSenderId: '377588042401',
    projectId: 'ecommers-e76c4',
    storageBucket: 'ecommers-e76c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZNx0uBaTkzIDf93B38m8OybvUGS9w_mA',
    appId: '1:377588042401:ios:13e4e50764e13401363ee0',
    messagingSenderId: '377588042401',
    projectId: 'ecommers-e76c4',
    storageBucket: 'ecommers-e76c4.appspot.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZNx0uBaTkzIDf93B38m8OybvUGS9w_mA',
    appId: '1:377588042401:ios:13e4e50764e13401363ee0',
    messagingSenderId: '377588042401',
    projectId: 'ecommers-e76c4',
    storageBucket: 'ecommers-e76c4.appspot.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKUUkZm6fN_AFKevUOuaMKRvQwIouVjqo',
    appId: '1:377588042401:web:55bc86da5d4c51ee363ee0',
    messagingSenderId: '377588042401',
    projectId: 'ecommers-e76c4',
    authDomain: 'ecommers-e76c4.firebaseapp.com',
    storageBucket: 'ecommers-e76c4.appspot.com',
    measurementId: 'G-Y1EYPB4RTX',
  );
}
